### PR TITLE
Add new custom plugin for better AWS Lambda Support

### PR DESCRIPTION
**Pull request by Dimitri-Gnidash**
- Add new availability zone
- Add plugin to `kong.conf`
- Add bash script to install the plugin using luarocks

### CODE REVIEW

**Comment by calvinlfer** [comment]
@Dimitri-Gnidash please let me know when this is ready for review

**Comment by Dimitri-Gnidash** [comment]
@calvinlfer Ready for review!

**Comment by Dimitri-Gnidash** [comment]
Ping @calvinlfer

**Review by calvinlfer — APPROVED** [review]
LGTM

**Comment by calvinlfer** [comment]
Just the docs on Confluence to configure the plugin would be good to have as well or perhaps it can go in the GitHub Wiki

**Comment by calvinlfer** [comment]
@Dimitri-Gnidash feel free to merge when ready

**Pull request merged**
