### PR TITLE
Added deployment bash script, parameters for optional config, address security risks

### PR DESCRIPTION
**Pull request by hackmad**
- Added parameters for s3 bucket and database identifier with defauls for backwards compatibility of existing stacks.
- Added deployment bash script to handle staged deployment
- Remove the admin access config and ingress rules from `0.0.0.0/0`, since the administration endpoints aren't secure enough
- Handle health checks properly by allowing access for ELBs via a VpcCIDR configuration.

### CODE REVIEW

**Review by calvinlfer — APPROVED** [review]
LGTM!, thanks for setting this up

**Review by calvinlfer — CHANGES_REQUESTED** [review]
Investigate EC2 instances dying

**Comment by hackmad** [comment]
[This commit](https://github.com/FreckleIOT/kong/pull/3/commits/5554f77ffb33f125ec75219882a42737b14d9869) the issue with the instances constantly getting replaced by the load balancer

**Review by calvinlfer — APPROVED** [review]
LGTM, awesome work!
Love the improved documentation and that you have removed the confusing option for administration

**Pull request merged**
